# general info
name: "your name"
description: "your description"
meta_description: "your meta description"

# config
markdown: redcarpet
highlighter: pygments

# includes
disqus:
google_analytics:

sass:
  style: :expanded

gems:
  - jekyll-sitemap
