# general info
name: "your name"
description: "your description"
meta_description: "your meta description"
baseurl:

# config
markdown: redcarpet
highlighter: rouge
permalink: /:title/
exclude:
    - node_modules
    - LICENSE
    - README.md
    - gulpfile.js
    - package.json
defaults:
    -
        scope:
            path: ""
            type: pages
        values:
            layout: page
    -
        scope:
            path: ""
            type: posts
        values:
            layout: post

# includes
disqus: narcisradu
google_analytics:
email: example@test.com

sass:
    style: :expanded

gems:
    - jekyll-sitemap
